-- Mendhaus commerce + RevenueOS instrumentation.
-- Run in a dedicated Supabase project (do not mix TributeReady memorial PII).
-- RevenueOS ledger tables: copy from packages/revenueos/schema.sql as well.

create extension if not exists pgcrypto;

create table if not exists public.mh_customers (
  id uuid primary key default gen_random_uuid(),
  email text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.mh_orders (
  id uuid primary key default gen_random_uuid(),
  customer_id uuid references public.mh_customers (id),
  email text not null,
  status text not null default 'awaiting_payment'
    check (status in (
      'awaiting_payment',
      'paid',
      'fulfilling',
      'shipped',
      'delivered',
      'cancelled',
      'refunded'
    )),
  items jsonb not null,
  subtotal_usd numeric(10,2) not null,
  shipping_usd numeric(10,2) not null,
  tax_usd numeric(10,2) not null default 0,
  gross_revenue_usd numeric(10,2) not null,
  cogs_usd numeric(10,2) not null,
  shipping_cost_usd numeric(10,2) not null,
  fulfillment_fee_usd numeric(10,2) not null,
  stripe_fee_usd numeric(10,2) not null default 0,
  estimated_profit_usd numeric(10,2) not null,
  realized_profit_usd numeric(10,2),
  stripe_session_id text unique,
  payment_intent_id text unique,
  tracking_number text,
  carrier text,
  supplier_order_id text,
  shipping_address jsonb,
  attribution jsonb not null default '{}'::jsonb,
  session_id uuid,
  created_at timestamptz not null default now(),
  paid_at timestamptz,
  shipped_at timestamptz,
  refunded_at timestamptz
);

create table if not exists public.mh_events (
  id bigint generated by default as identity primary key,
  event_id uuid unique,
  event_name text not null,
  session_id uuid not null,
  product_id text,
  order_id uuid,
  attribution jsonb not null default '{}'::jsonb,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.mh_events
  add column if not exists event_id uuid;
create unique index if not exists mh_events_event_id_unique
  on public.mh_events (event_id)
  where event_id is not null;

create table if not exists public.mh_journal (
  id bigint generated by default as identity primary key,
  kind text not null default 'decision',
  summary text not null,
  detail jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.mh_supplier_listings (
  product_id text primary key,
  network text not null,
  supplier_product_id text not null,
  supplier_sku text,
  unit_cost_usd numeric(10,2),
  stock integer,
  hero_url text,
  gallery jsonb not null default '[]'::jsonb,
  warehouse_country text,
  search_query text,
  synced_at timestamptz not null default now(),
  payload jsonb not null default '{}'::jsonb
);

-- Reviews are only created after a delivered order is verified. There is no
-- public insert policy: a signed, single-use review invitation must be
-- validated by the server before a review can enter this table.
create table if not exists public.mh_product_reviews (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.mh_orders (id) on delete cascade,
  product_id text not null,
  rating smallint not null check (rating between 1 and 5),
  title text check (char_length(title) <= 120),
  body text not null check (char_length(body) between 20 and 2000),
  display_name text check (char_length(display_name) <= 80),
  status text not null default 'pending'
    check (status in ('pending', 'published', 'rejected')),
  created_at timestamptz not null default now(),
  published_at timestamptz,
  unique (order_id, product_id)
);

create index if not exists mh_orders_status_idx on public.mh_orders (status, created_at desc);
create index if not exists mh_events_session_idx on public.mh_events (session_id, created_at desc);
create index if not exists mh_events_name_idx on public.mh_events (event_name, created_at desc);
create index if not exists mh_events_created_idx on public.mh_events (created_at desc);
create index if not exists mh_events_product_idx on public.mh_events (product_id, created_at desc);
create index if not exists mh_journal_created_idx on public.mh_journal (created_at desc);
create unique index if not exists mh_journal_kind_summary_unique
  on public.mh_journal (kind, summary)
  where kind in ('hourly_email', 'revenueos_cycle', 'stripe_event', 'revenueos_launch');
create index if not exists mh_supplier_listings_synced_idx on public.mh_supplier_listings (synced_at desc);
create index if not exists mh_product_reviews_public_idx
  on public.mh_product_reviews (product_id, created_at desc)
  where status = 'published';

alter table public.mh_customers enable row level security;
alter table public.mh_orders enable row level security;
alter table public.mh_events enable row level security;
alter table public.mh_journal enable row level security;
alter table public.mh_supplier_listings enable row level security;
alter table public.mh_product_reviews enable row level security;

-- Live merchandising state RevenueOS can mutate (single-row document).
create table if not exists public.mh_merch_state (
  id text primary key default 'live',
  document jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  updated_by text not null default 'system'
);

insert into public.mh_merch_state (id, document, updated_by)
values ('live', '{}'::jsonb, 'bootstrap')
on conflict (id) do nothing;

alter table public.mh_merch_state enable row level security;

-- Internet research + published intent topics RevenueOS mutates.
create table if not exists public.mh_discovery_state (
  id text primary key default 'live',
  document jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  updated_by text not null default 'system'
);

insert into public.mh_discovery_state (id, document, updated_by)
values ('live', '{}'::jsonb, 'bootstrap')
on conflict (id) do nothing;

alter table public.mh_discovery_state enable row level security;
