-- Mendhaus commerce + RevenueOS instrumentation.
-- Run in a dedicated Supabase project (do not mix TributeReady memorial PII).
-- RevenueOS ledger tables: copy from packages/revenueos/schema.sql as well.

create extension if not exists pgcrypto;

create table if not exists public.mh_customers (
  id uuid primary key default gen_random_uuid(),
  email text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.mh_orders (
  id uuid primary key default gen_random_uuid(),
  customer_id uuid references public.mh_customers (id),
  email text not null,
  status text not null default 'awaiting_payment'
    check (status in (
      'awaiting_payment',
      'paid',
      'fulfilling',
      'shipped',
      'delivered',
      'cancelled',
      'refunded'
    )),
  items jsonb not null,
  subtotal_usd numeric(10,2) not null,
  shipping_usd numeric(10,2) not null,
  tax_usd numeric(10,2) not null default 0,
  gross_revenue_usd numeric(10,2) not null,
  cogs_usd numeric(10,2) not null,
  shipping_cost_usd numeric(10,2) not null,
  fulfillment_fee_usd numeric(10,2) not null,
  stripe_fee_usd numeric(10,2) not null default 0,
  estimated_profit_usd numeric(10,2) not null,
  realized_profit_usd numeric(10,2),
  stripe_session_id text unique,
  payment_intent_id text unique,
  tracking_number text,
  carrier text,
  supplier_order_id text,
  shipping_address jsonb,
  attribution jsonb not null default '{}'::jsonb,
  session_id uuid,
  created_at timestamptz not null default now(),
  paid_at timestamptz,
  shipped_at timestamptz,
  refunded_at timestamptz
);

create table if not exists public.mh_events (
  id bigint generated by default as identity primary key,
  event_name text not null,
  session_id uuid not null,
  product_id text,
  order_id uuid,
  attribution jsonb not null default '{}'::jsonb,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.mh_journal (
  id bigint generated by default as identity primary key,
  kind text not null default 'decision',
  summary text not null,
  detail jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.mh_supplier_listings (
  product_id text primary key,
  network text not null,
  supplier_product_id text not null,
  supplier_sku text,
  unit_cost_usd numeric(10,2),
  stock integer,
  hero_url text,
  gallery jsonb not null default '[]'::jsonb,
  warehouse_country text,
  search_query text,
  synced_at timestamptz not null default now(),
  payload jsonb not null default '{}'::jsonb
);

create index if not exists mh_orders_status_idx on public.mh_orders (status, created_at desc);
create index if not exists mh_events_session_idx on public.mh_events (session_id, created_at desc);
create index if not exists mh_events_name_idx on public.mh_events (event_name, created_at desc);
create index if not exists mh_events_created_idx on public.mh_events (created_at desc);
create index if not exists mh_events_product_idx on public.mh_events (product_id, created_at desc);
create index if not exists mh_journal_created_idx on public.mh_journal (created_at desc);
create index if not exists mh_supplier_listings_synced_idx on public.mh_supplier_listings (synced_at desc);

alter table public.mh_customers enable row level security;
alter table public.mh_orders enable row level security;
alter table public.mh_events enable row level security;
alter table public.mh_journal enable row level security;
alter table public.mh_supplier_listings enable row level security;
