/**
 * Gateway config writer — Caddyfile for domain → static artifact or process port.
 * Hosting plane configures the proxy; Caddy is the public edge.
 */

import { mkdirSync, writeFileSync, existsSync } from "node:fs";
import path from "node:path";
import type { SiteRuntimeRecord } from "./runtime/types.js";

const STOREFRONT_API =
  process.env.HOSTING_STOREFRONT_API || "127.0.0.1:8091";

export function writeCaddyfile(input: {
  outDir: string;
  sites: SiteRuntimeRecord[];
  email?: string;
}): string {
  mkdirSync(input.outDir, { recursive: true });
  // Sites fragment only — imported by /etc/caddy/Caddyfile (no nested global block).
  const lines: string[] = [
    `# Generated by RevenueOS Hosting Plane — do not edit by hand`,
    ``,
  ];

  for (const site of input.sites) {
    if (site.status === "retired" || site.status === "stopped") continue;
    const domains = site.domains.length
      ? site.domains
      : [`${site.siteId}.localhost`];
    for (const domain of domains) {
      lines.push(`${domain} {`);
      lines.push(`  encode gzip`);
      lines.push(`  log {`);
      lines.push(`    output file /var/log/caddy/access.log {`);
      lines.push(`      roll_size 50mb`);
      lines.push(`      roll_keep 10`);
      lines.push(`    }`);
      lines.push(`    format json`);
      lines.push(`  }`);
      lines.push(`  handle /api/* {`);
      lines.push(`    reverse_proxy ${STOREFRONT_API}`);
      lines.push(`  }`);
      if (site.runtimeKind === "static" && site.artifactDir) {
        lines.push(`  handle {`);
        lines.push(`    root * ${site.artifactDir}`);
        lines.push(`    try_files {path} {path}/ {path}/index.html /index.html`);
        lines.push(`    file_server`);
        lines.push(`  }`);
      } else if (site.port) {
        lines.push(`  handle {`);
        lines.push(`    reverse_proxy 127.0.0.1:${site.port}`);
        lines.push(`  }`);
      } else {
        lines.push(`  respond "site not ready" 503`);
      }
      lines.push(`}`);
      lines.push(``);
    }
  }

  const file = path.join(input.outDir, "Caddyfile.sites");
  writeFileSync(file, lines.join("\n"), "utf8");
  // Also write full Caddyfile for standalone use
  writeFileSync(path.join(input.outDir, "Caddyfile"), lines.join("\n"), "utf8");
  return file;
}

export function writeNginxSnippet(input: {
  outDir: string;
  sites: SiteRuntimeRecord[];
}): string {
  mkdirSync(input.outDir, { recursive: true });
  const lines: string[] = [`# Generated by RevenueOS Hosting Plane`];
  for (const site of input.sites) {
    if (site.status === "retired" || site.status === "stopped") continue;
    const domains = site.domains.length
      ? site.domains
      : [`${site.siteId}.localhost`];
    lines.push(`# ${site.siteId}`);
    lines.push(`server {`);
    lines.push(`  listen 80;`);
    lines.push(`  server_name ${domains.join(" ")};`);
    lines.push(`  location /api/ {`);
    lines.push(`    proxy_pass http://${STOREFRONT_API};`);
    lines.push(`  }`);
    if (site.runtimeKind === "static" && site.artifactDir) {
      lines.push(`  location / {`);
      lines.push(`    root ${site.artifactDir};`);
      lines.push(`    try_files $uri $uri/ /index.html;`);
      lines.push(`  }`);
    } else if (site.port) {
      lines.push(`  location / {`);
      lines.push(`    proxy_pass http://127.0.0.1:${site.port};`);
      lines.push(`  }`);
    }
    lines.push(`}`);
    lines.push(``);
  }
  const file = path.join(input.outDir, "nginx-sites.conf");
  writeFileSync(file, lines.join("\n"), "utf8");
  return file;
}

export function gatewayPathsExist(outDir: string) {
  return {
    caddy: existsSync(path.join(outDir, "Caddyfile")),
    nginx: existsSync(path.join(outDir, "nginx-sites.conf")),
  };
}
