/**
 * Gateway config writer — Caddyfile / nginx snippets for domain → port routing.
 * Hosting plane does not become the public server itself; it configures the proxy.
 */

import { mkdirSync, writeFileSync, existsSync } from "node:fs";
import path from "node:path";
import type { SiteRuntimeRecord } from "./runtime/types.js";

export function writeCaddyfile(input: {
  outDir: string;
  sites: SiteRuntimeRecord[];
  email?: string;
}): string {
  mkdirSync(input.outDir, { recursive: true });
  const lines: string[] = [
    `# Generated by RevenueOS Hosting Plane — do not edit by hand`,
    `{`,
    `  email ${input.email ?? "ops@revenueos.local"}`,
    `}`,
    ``,
  ];

  for (const site of input.sites) {
    if (site.status === "retired" || site.status === "stopped") continue;
    if (!site.port) continue;
    const domains = site.domains.length ? site.domains : [`${site.siteId}.localhost`];
    for (const domain of domains) {
      lines.push(`${domain} {`);
      lines.push(`  reverse_proxy 127.0.0.1:${site.port}`);
      lines.push(`  encode gzip`);
      lines.push(`}`);
      lines.push(``);
    }
  }

  const file = path.join(input.outDir, "Caddyfile");
  writeFileSync(file, lines.join("\n"), "utf8");
  return file;
}

export function writeNginxSnippet(input: {
  outDir: string;
  sites: SiteRuntimeRecord[];
}): string {
  mkdirSync(input.outDir, { recursive: true });
  const lines: string[] = [`# Generated by RevenueOS Hosting Plane`];
  for (const site of input.sites) {
    if (site.status === "retired" || site.status === "stopped" || !site.port) continue;
    const domains = site.domains.length ? site.domains : [`${site.siteId}.localhost`];
    lines.push(`# ${site.siteId}`);
    lines.push(`server {`);
    lines.push(`  listen 80;`);
    lines.push(`  server_name ${domains.join(" ")};`);
    lines.push(`  location / {`);
    lines.push(`    proxy_pass http://127.0.0.1:${site.port};`);
    lines.push(`    proxy_set_header Host $host;`);
    lines.push(`    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;`);
    lines.push(`    proxy_set_header X-Forwarded-Proto $scheme;`);
    lines.push(`  }`);
    lines.push(`}`);
    lines.push(``);
  }
  const file = path.join(input.outDir, "nginx-sites.conf");
  writeFileSync(file, lines.join("\n"), "utf8");
  return file;
}

export function gatewayPathsExist(outDir: string) {
  return {
    caddy: existsSync(path.join(outDir, "Caddyfile")),
    nginx: existsSync(path.join(outDir, "nginx-sites.conf")),
  };
}
